### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by TaiChi01** [XiaoHuiHui233/MonitorR#1]
一个是再windows下面:不能作为文件名存在，
`time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')`
把:去掉就可以了；
还有一个没检查records文件夹是否存在，默认之前插件留存这个文件夹就不报错，但是全新创建服务器一直报错
`config_folder = f"./config/{PLUGIN_METADATA['id']}"`
`log_folder = f'{config_folder}/logs'`
`log_file = f'{log_folder}/log.json'`
`site_file = f'{config_folder}/site.json'`
`config_file = f'{config_folder}/config.json'`

`def split_log() -> None:`
`    global record_fp`
`    if os.path.exists(log_file):`
`        time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')`
`        os.rename(log_file, f'./records/{time}.json')`
`    if not os.path.exists(config_folder):`
`        os.makedirs(config_folder)`
`    if not os.path.exists(log_folder):`
 `       os.makedirs(log_folder)`
 `   record_fp = open(log_file, 'w+', encoding='utf-8')
`

**Comment by XiaoHuiHui233** [comment]
Fixed.

For the first bug. The format expression of date has been changed to "%Y_%m_%d_%H_%M_%S" which is not graceful but just useful.
For the second bug. The record folder is not what I want to design. It just appears because I copied the code of the Monitor plugin and at first just wanted to make minor changes on it. So that folder should be the logs folder.

At last, thank you very much for raising this bug issue. Hint: Please send PR directly next time :)
